---------------  系统表  -----------------

-------------------
--    字典表     --
-------------------

-- CREATE TABLE
CREATE TABLE APMS_SYS_DICT
(
  DICT_ID        NUMBER(9) NOT NULL,
  DICT_PARENT_ID NUMBER(9),
  DICT_NATURE    VARCHAR2(30) NOT NULL,
  DICT_CODE      VARCHAR2(50) NOT NULL,
  DICT_VALUE     VARCHAR2(100) NOT NULL,
  DICT_DESC      VARCHAR2(50),
  IS_ENABLED     VARCHAR2(1) DEFAULT 1 NOT NULL
)
TABLESPACE APMS
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS
ALTER TABLE APMS_SYS_DICT
  ADD CONSTRAINT APMS_SYS_DICT_KEY PRIMARY KEY (DICT_ID);
-- ADD COMMENTS TO THE TABLE
COMMENT ON TABLE APMS_SYS_DICT
  IS '字典表';
-- ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN APMS_SYS_DICT.DICT_ID
  IS 'ID';
COMMENT ON COLUMN APMS_SYS_DICT.DICT_PARENT_ID
  IS '上级字典，往往直接是类型描述，除非是父子结构的';
COMMENT ON COLUMN APMS_SYS_DICT.DICT_NATURE
  IS '类型';
COMMENT ON COLUMN APMS_SYS_DICT.DICT_CODE
  IS '编码';
COMMENT ON COLUMN APMS_SYS_DICT.DICT_VALUE
  IS '显示值';
COMMENT ON COLUMN APMS_SYS_DICT.DICT_DESC
  IS '描述，只有类型描述的项需要填写这个';
COMMENT ON COLUMN APMS_SYS_DICT.IS_ENABLED
  IS '是否启用，1启用，其他，禁用';


-------------------
--    功能表     --
-------------------

-- CREATE TABLE
CREATE TABLE APMS_SYS_FUNC
(
  FUNC_ID          NUMBER(9) NOT NULL,
  FUNC_PARENT_ID   NUMBER(9),
  FUNC_CODE        VARCHAR2(30) NOT NULL,
  FUNC_NAME        VARCHAR2(20) NOT NULL,
  FUNC_TYPE        VARCHAR2(10) NOT NULL,
  FUNC_URL         VARCHAR2(100),
  FUNC_DESC        VARCHAR2(100),
  FUNC_SEQ         NUMBER(2) NOT NULL,
  FUNC_ICON        VARCHAR2(30) NOT NULL,
  FUNC_IS_BUILT_IN VARCHAR2(1) DEFAULT 1 NOT NULL,
  IS_ENABLED       VARCHAR2(1) DEFAULT 1 NOT NULL,
  IS_VISIBLE       VARCHAR2(1) DEFAULT 1 NOT NULL
)
TABLESPACE APMS
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS
ALTER TABLE APMS_SYS_FUNC
  ADD CONSTRAINT APMS_SYS_FUNC_KEY PRIMARY KEY (FUNC_ID);
-- ADD COMMENTS TO THE TABLE
COMMENT ON TABLE APMS_SYS_FUNC
  IS '功能菜表';
-- ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_ID
  IS 'ID';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_PARENT_ID
  IS '上级功能';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_CODE
  IS '功能编码，前台需要解析';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_NAME
  IS '功能需要显示的名称';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_TYPE
  IS '功能类型，ROOT(根),GROUP(分组),MENU(菜单),LINK(链接),FUNC(功能菜单),ACTION(行为)';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_URL
  IS '如果是连接，则设置此URL';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_DESC
  IS '功能说明';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_SEQ
  IS '功能在同级排序的序号';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_ICON
  IS '功能在显示时，同时需要显示的图标的CSS样式';
COMMENT ON COLUMN APMS_SYS_FUNC.FUNC_IS_BUILT_IN
  IS '是否内嵌，针对LINK(链接),FUNC(功能菜单)关联的页面是否是内嵌到屏主功能页面内，如果不是，则弹出。';
COMMENT ON COLUMN APMS_SYS_FUNC.IS_ENABLED
  IS '是否启用，1启用，其他，禁用';
COMMENT ON COLUMN APMS_SYS_FUNC.IS_VISIBLE
  IS '是否可见，1启用，其他，禁用';


-------------------
--    用户表     --
-------------------

-- CREATE TABLE
CREATE TABLE APMS_SYS_USER
(
  USER_ID      NUMBER(9) NOT NULL,
  STATION_ID   NUMBER(9) NOT NULL,
  USER_NAME    VARCHAR2(16) NOT NULL,
  USER_TEL     VARCHAR2(16) NOT NULL,
  USER_MOBILE  VARCHAR2(16) NOT NULL,
  USER_MAIL    VARCHAR2(64),
  USER_ACCOUNT VARCHAR2(30) NOT NULL,
  USER_PWD     VARCHAR2(64) NOT NULL,
  USER_PHOTO   CLOB NOT NULL,
  IS_ENABLED   VARCHAR2(1) DEFAULT 1 NOT NULL
)
TABLESPACE APMS
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS
ALTER TABLE APMS_SYS_USER
  ADD CONSTRAINT APMS_SYS_USER_KEY PRIMARY KEY (USER_ID);
-- ADD COMMENTS TO THE TABLE
COMMENT ON TABLE APMS_SYS_USER
  IS '用户表';
-- ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN APMS_SYS_USER.USER_ID
  IS 'ID';
COMMENT ON COLUMN APMS_SYS_USER.STATION_ID
  IS '科所队ID';
COMMENT ON COLUMN APMS_SYS_USER.USER_NAME
  IS '用户名称';
COMMENT ON COLUMN APMS_SYS_USER.USER_TEL
  IS '联系电话';
COMMENT ON COLUMN APMS_SYS_USER.USER_MOBILE
  IS '手机号码';
COMMENT ON COLUMN APMS_SYS_USER.USER_MAIL
  IS '邮箱';
COMMENT ON COLUMN APMS_SYS_USER.USER_ACCOUNT
  IS '用户帐号';
COMMENT ON COLUMN APMS_SYS_USER.USER_PWD
  IS '用户密码';
COMMENT ON COLUMN APMS_SYS_USER.USER_PHOTO
  IS '用户头像';
COMMENT ON COLUMN APMS_SYS_USER.IS_ENABLED
  IS '是否启用，1启用，其他，禁用';


----------------------------
--    用户功能关联表      --
----------------------------

-- CREATE TABLE
CREATE TABLE APMS_SYS_USER_FUNC
(
  REL_ID  NUMBER(9) NOT NULL,
  USER_ID NUMBER(9) NOT NULL,
  FUNC_ID NUMBER(9) NOT NULL
)
TABLESPACE APMS
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS
ALTER TABLE APMS_SYS_USER_FUNC
  ADD CONSTRAINT APMS_SYS_USER_FUNC_KEY PRIMARY KEY (REL_ID);
-- ADD COMMENTS TO THE TABLE
COMMENT ON TABLE APMS_SYS_USER_FUNC
  IS '用户功能关联表';
-- ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN APMS_SYS_USER_FUNC.REL_ID
  IS 'ID';
COMMENT ON COLUMN APMS_SYS_USER_FUNC.USER_ID
  IS '用户ID';
COMMENT ON COLUMN APMS_SYS_USER_FUNC.FUNC_ID
  IS '功能ID';

