ALTER TABLE "C##APMS"."APMS_ATTACHMENT" MODIFY ( "ATT_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_ATTACHMENT" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_INFO" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_APPRAISE" MODIFY ( "APPR_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_APPRAISE" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_APPRAISE" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_AWARD" MODIFY ( "AWARD_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_AWARD" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_AWARD" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_EDUCATION" MODIFY ( "EDU_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_EDUCATION" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_EDUCATION" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_FAMILY" MODIFY ( "FAMILY_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_FAMILY" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_FAMILY" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_PUNISH" MODIFY ( "PUNISH_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_PUNISH" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_PUNISH" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_STUFF_FILE" MODIFY ( "FILE_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_STUFF_FILE" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_STUFF_FILE" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_AUX_WORK" MODIFY ( "WORK_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_WORK" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_AUX_WORK" MODIFY ( "AUX_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_DEPT_BUREAU" MODIFY ( "BUREAU_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_DEPT_BUREAU" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_DEPT_STATION" MODIFY ( "STATION_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_DEPT_STATION" MODIFY ( "BUREAU_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_DEPT_STATION" MODIFY ( "LATEST_UPDATE_USER" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_SYS_DICT" MODIFY ( "DICT_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_SYS_DICT" MODIFY ( "DICT_PARENT_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_SYS_FUNC" MODIFY ( "FUNC_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_SYS_FUNC" MODIFY ( "FUNC_PARENT_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_SYS_USER" MODIFY ( "USER_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_SYS_USER" MODIFY ( "STATION_ID" VARCHAR2(36 BYTE) ) ;

ALTER TABLE "C##APMS"."APMS_SYS_USER_FUNC" MODIFY ( "REL_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_SYS_USER_FUNC" MODIFY ( "FUNC_ID" VARCHAR2(36 BYTE) ) ;
ALTER TABLE "C##APMS"."APMS_SYS_USER_FUNC" MODIFY ( "USER_ID" VARCHAR2(36 BYTE) ) ;