ALTER TABLE "C##APMS"."APMS_AUX_INFO"
ADD ( "AUX_SALARY_BASE" NUMBER(5) NULL  )
ADD ( "AUX_SALARY_BONUS" NUMBER(5) NULL  )
ADD ( "AUX_SALARY_TAX" NUMBER(5) NULL  )
ADD ( "AUX_SALARY_S_SS" NUMBER(5) NULL  )
ADD ( "AUX_SALARY_S_FUND" NUMBER(5) NULL  )
ADD ( "AUX_SALARY_C_SS" NUMBER(5) NULL  )
ADD ( "AUX_SALARY_C_FUND" NUMBER(5) NULL  ) ;

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_BASE" IS '基本工资';

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_BONUS" IS '奖金';

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_TAX" IS '所得税';

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_S_SS" IS '个付 社保social security';

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_S_FUND" IS '个付公积金';

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_C_SS" IS '司付社保';

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_C_FUND" IS '司付公积金';


ALTER TABLE "C##APMS"."APMS_AUX_INFO"
ADD ( "AUX_SALARY_S_GET" NUMBER(5) NULL  )
ADD ( "AUX_SALARY_C_PAY" NUMBER(5) NULL  ) ;

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_S_GET" IS '实发工资';

COMMENT ON COLUMN "C##APMS"."APMS_AUX_INFO"."AUX_SALARY_C_PAY" IS '司付工资';

