ALTER TABLE "APMS"."APMS_DEPT_STATION"
ADD ( "IS_MANAGE" VARCHAR2(1) default 0);

COMMENT ON COLUMN "APMS"."APMS_DEPT_STATION"."IS_MANAGE" IS '是否是管理单位，1是';

ALTER TABLE "APMS"."APMS_AUX_APPRAISE"
ADD ( "APPR_TYPE" VARCHAR2(1) default 0)
ADD ( "APPR_NUM" VARCHAR2(1) default 0);

COMMENT ON COLUMN "APMS"."APMS_AUX_APPRAISE"."APPR_TYPE" IS '考核类型';
COMMENT ON COLUMN "APMS"."APMS_AUX_APPRAISE"."APPR_NUM" IS '考核季度或月份';

ALTER TABLE "APMS"."APMS_AUX_INFO"
ADD ( "AUX_SALARY_GWGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_GLGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_ZJGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_JTGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_JFLY" VARCHAR2(20) NULL)
ADD ( "AUX_RYZT" VARCHAR2(20) NULL);

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_GWGZ" IS '岗位工资';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_GLGZ" IS '工龄工资';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_ZJGZ" IS '职级工资';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_JTGZ" IS '工龄津贴';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_JFLY" IS '经费来源';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_RYZT" IS '人员状态';