ALTER TABLE "APMS"."APMS_DEPT_STATION"
ADD ( "IS_MANAGE" VARCHAR2(1) default 0);

COMMENT ON COLUMN "APMS"."APMS_DEPT_STATION"."IS_MANAGE" IS '是否是管理单位，1是';

ALTER TABLE "APMS"."APMS_AUX_APPRAISE"
ADD ( "APPR_TYPE" VARCHAR2(1) default 0)
ADD ( "APPR_NUM" VARCHAR2(1) default 0);

COMMENT ON COLUMN "APMS"."APMS_AUX_APPRAISE"."APPR_TYPE" IS '考核类型';
COMMENT ON COLUMN "APMS"."APMS_AUX_APPRAISE"."APPR_NUM" IS '考核季度或月份';

ALTER TABLE "APMS"."APMS_AUX_INFO"
ADD ( "AUX_SALARY_GWGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_GLGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_ZJGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_JTGZ" NUMBER(5) NULL)
ADD ( "AUX_SALARY_JFLY" VARCHAR2(20) NULL)
ADD ( "AUX_RYZT" VARCHAR2(20) NULL);

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_GWGZ" IS '岗位工资';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_GLGZ" IS '工龄工资';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_ZJGZ" IS '职级工资';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_JTGZ" IS '工龄津贴';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_SALARY_JFLY" IS '经费来源';

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_RYZT" IS '人员状态';

--需求补充添加信息
ALTER TABLE "APMS"."APMS_AUX_INFO"
ADD ( "AUX_ORGANIZE_DATE" VARCHAR2(30) NULL)
ADD ( "AUX_WORK_DATE" VARCHAR2(30) NULL)
ADD ( "AUX_EMPLOY_UNIT" VARCHAR2(100) NULL));

COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_ORGANIZE_DATE" IS '参加组织时间';
COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_WORK_DATE" IS '参加工作时间';
COMMENT ON COLUMN "APMS"."APMS_AUX_INFO"."AUX_EMPLOY_UNIT" IS '聘用主体信息';

ALTER TABLE "APMS"."APMS_AUX_WORK"
ADD ( "WORK_POST" VARCHAR2(30) NULL));

COMMENT ON COLUMN "APMS"."APMS_AUX_WORK"."WORK_POST" IS '职位';


CREATE TABLE "APMS"."APMS_AUX_CASUALTY" (
"CAS_ID" VARCHAR2(36) NOT NULL ,
"CAS_DATE" VARCHAR2(30) NULL ,
"CAS_PLACE" VARCHAR2(200) NULL ,
"CAS_TYPE" VARCHAR2(30) NULL ,
"CAS_REMAKE" VARCHAR2(500) NULL ,
"CAS_FSCD" VARCHAR2(30) NULL ,
"CAS_SCCD" VARCHAR2(30) NULL ,
"LATEST_UPDATE_USER" VARCHAR2(36) NULL ,
"LATEST_UPDATE_DATE" VARCHAR2(30) NULL ,
"LATEST_UPDATE_IP" VARCHAR2(40) NULL ,
"AUX_ID" VARCHAR2(36) NULL
);

COMMENT ON TABLE "APMS"."APMS_AUX_CASUALTY" IS '辅警伤亡信息';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."CAS_ID" IS 'ID';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."CAS_DATE" IS '时间';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."CAS_PLACE" IS '地点';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."CAS_TYPE" IS '种类';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."CAS_REMAKE" IS '详情';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."CAS_FSCD" IS '负伤程度';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."CAS_SCCD" IS '伤残程度';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."LATEST_UPDATE_USER" IS '最近更新人ID与用户表关联';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."LATEST_UPDATE_DATE" IS '最近更新时间';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."LATEST_UPDATE_IP" IS '最近更新IP';
COMMENT ON COLUMN "APMS"."APMS_AUX_CASUALTY"."AUX_ID" IS '辅警ID';

CREATE INDEX "APMS"."APMS_AUX_CASUALTY_IDX_ID"
ON "APMS"."APMS_AUX_CASUALTY" ("CAS_ID" ASC)
LOGGING
VISIBLE;

ALTER TABLE "APMS"."APMS_AUX_CASUALTY" ADD PRIMARY KEY ("CAS_ID");



